
```{r}
library(httr2)
library(rvest)
library(tidyverse)
library(lubridate)
source("teams_fns.R")
source("soccerway_fns.R")
source("comp_fns.R")
source("update.R")
source("getting-games.R")
```
## initialize from previous

```{r}
games <- read_rds("games.rds")
teams <- read_rds("teams.rds")
comps <- read_rds("comps.rds")
```


## update

```{r}
game_ids <- results_to_get(10)
game_ids
```

get some random ones

```{r}
base <- 3451637
delta <-     10  
game_ids <- random_fixtures(base-delta, base+delta, 20)
length(game_ids)
```

```{r}
update_everything(game_ids)
display_games() %>% arrange(desc(retrieved)) %>% View("these games")
```

find lower and upper limit of this league


```{r}
this_game <- 3451646
game_limits <- league_limits(this_game)
game_limits
```

```{r}
get_league(this_game)
display_games() %>% 
  filter(between(game, game_limits[1], game_limits[2])) %>% 
  arrange(game) %>% 
  View("these games")
```

make a table of leagues with games


```{r}
wanted <- read_rds("../ratings/league_ids.rds")
l <- league_games()
wanted %>% left_join(l, by = c("id"="comp")) %>% View("comps")
sample(1:112, 1)
```

```{r}
display_games() %>% View("games")
```

find biggest match gaps

```{r}
games <- read_rds("games.rds")
games %>% arrange(game) %>% 
  select(game) %>% 
  mutate(last_game = lag(game), 
         difference = game - last_game) %>% 
  arrange(desc(difference)) -> dd1
dd1
```

```{r}
game_ids <- random_fixtures(dd1$last_game[1], dd1$game[1], 100)
update_everything(game_ids)
display_games() %>% arrange(desc(retrieved)) %>% View("these games")
```


save as feather/fst (latter smaller)

```{r}
# library(feather)
# write_feather(games, "g.feather")
library(fst)
write_fst(games, "g.fst")
```

remove a game

```{r}
rem <- 3582303
games <- read_rds("games.rds")
nrow(games)
games %>%  filter(game != rem) -> games
nrow(games)
write_rds(games, "games.rds")
```

